### ISSUE TITLE
Add Exam Score : Make Exam word case insensitive 

### ISSUE THREAD

**Issue by Shruthiiii03** [AY2425S1-CS2103-F12-4/tp#141]
(not under v1.4) A suggestion is that while trying to add the exam score, if the teachers mix up the lower or upper case, the exam word could be made case insensitive so no issue would rise if the below scenario occurs.  

<img width="864" alt="Screenshot 2024-11-01 at 10 46 31 PM" src="https://github.com/user-attachments/assets/ac6e3043-867e-428c-aa57-e25c41f501d7">

**Comment by jason-chuah** [comment]
The student name field is also case sensitive, so for now we have decided to leave it as case sensitive for consistency. This is the same for submission name. It has been reflected in the UG.
