### ISSUE TITLE
[PE-D][Tester B] DG Use case

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F12-4/tp#233]
![image.png](https://raw.githubusercontent.com/Sornsornah/ped/main/files/173d64f8-9f8d-43fa-8566-78c37d1018ba.png)

Suggestion: Would be good to have “Use case ends.” on the next line to make it clearer.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Sornsornah/ped#3

**Comment by gohqingkhang** [comment]
update dg
