### ISSUE TITLE
[PE-D][Tester B] Different behaviour for edit command for single-valued inputs

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F12-4/tp#248]
Edit of 2 register numbers provided (accepted input, when it should not)
![image.png](https://raw.githubusercontent.com/Sornsornah/ped/main/files/254ab09e-4414-47ad-b46d-f770261b2dee.png)
Edit of 2 names provided (rejected input, performs as expected)
![image.png](https://raw.githubusercontent.com/Sornsornah/ped/main/files/a301b710-97ca-4731-8395-ae83cebcc489.png)

Steps to Reproduce:
`edit 1 n/Alex Yeoh n/Alan Tan`
`edit 1 r/1 r/2`

Expected: Editing register number when 2 values are provided should return error `Multiple values specified for the following single-valued field(s): r/`
Actual: Input is accepted and takes the second value, even though user might want the first number instead
Suggestion: Standardise the edit command to reject inputs if there are multiple values specified for single valued fields

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Sornsornah/ped#7

**Comment by gohqingkhang** [comment]
check if same issue for sex and class
