### ISSUE TITLE
[PE-D][Tester E] Add Emergency Number command summary typo

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F12-4/tp#250]
The command for Add Emergency Number is typed wrong.
# Expected Outcome
AddEcNumber
# Actual Outcome
EcNumber
![image.png](https://raw.githubusercontent.com/george-yeo/ped/main/files/c276e61e-5521-4d0b-8bee-801a40a78691.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: george-yeo/ped#2

**Comment by BunnyHoppp** [comment]
Fixed
