### ISSUE TITLE
[PE-D][Tester C] Exam scores forced to 1 decimal point

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F12-4/tp#266]
![image.png](https://raw.githubusercontent.com/anselmlong/ped/main/files/e5e27afc-02ba-41a0-9c55-4daaafbd9895.png)

The program doesn't allow me to enter whole numbers for the scores. As a user, my exam scores may just be whole numbers, and forcing me to add a decimal point seems redundant.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: anselmlong/ped#20

**Comment by jason-chuah** [comment]
addressed in another issue
