### ISSUE TITLE
[PE-D][Tester C] Submission status case-sensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F12-4/tp#271]
> The submission status must be "Y", "N" or NIL

As a user, it would be easier to just write "y" as "Y" requires an extra keystroke. Making this case-insensitive will be beneficial.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: anselmlong/ped#22

**Comment by gohqingkhang** [comment]
enhancement
