### ISSUE TITLE
[PE-D][Tester C] Inconsistent capitalisation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F12-4/tp#297]
> The Architecture Diagram given above explains the high-level design of the App.

App is capitalised here but not in here:

> Main (consisting of classes Main and MainApp ) is in charge of the app launch and shut down

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: anselmlong/ped#32

**Comment by gohqingkhang** [comment]
update
