### ISSUE TITLE
[PE-D][Tester C] Wrong information in Use Case 02

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F12-4/tp#310]
In UC02, you state that 

> 3b1. System displays an error message notifying that the email already exists in the system. Use case ends.

However, your system allows duplicate emails.

![image.png](https://raw.githubusercontent.com/anselmlong/ped/main/files/bd9a525e-c8b5-48d4-86e6-107d4db8e0fd.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: anselmlong/ped#38

**Comment by gohqingkhang** [comment]
update DG
