### ISSUE TITLE
[PE-D][Tester A] Confusing info in DG: `Preconditions: User is logged in.`

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F12-4/tp#326]
![Screenshot 2024-11-08 at 5.57.59 PM.png](https://raw.githubusercontent.com/SeeYangZhi/ped/main/files/90f06a80-ff4d-4366-b115-7c0f177158e1.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: SeeYangZhi/ped#18

**Comment by gohqingkhang** [comment]
rewrite to "app is opened"
